
site_name: Trust Network Guidelines
theme:
  name: material
  palette:
    scheme: default
    primary: custom
    accent: custom
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.annotate
    - content.code.copy
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Materials: materials.md
  - Procedure: procedure.md
  - Analysis: analysis.md
  - About: about.md
